spring:
  application:
    name: wallet-withdrawals
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:walletwithdrawals}
    username: ${DB_USERNAME:walletwithdrawals}
    password: ${DB_PASSWORD:walletwithdrawals}
    driver-class-name: org.postgresql.Driver

  jooq:
    sql-dialect: postgres
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    validate-migration-naming: true

# Logging
logging:
  level:
    com.teixeirah.withdrawals: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %msg%n"


adapters:
  wallet-service:
    base-url: "http://mockoon.tools.getontop.com:3000"
  payment-provider:
    base-url: "http://mockoon.tools.getontop.com:3000"
  payment-source:
    type: "COMPANY"
    source-information:
      name: "ONTOP INC"
    account:
      account-number: "0245253419"
      currency: "USD"
      routing-number: "028444018"

# --- Resilience4j Configuration ---
resilience4j:
  # --- Time Limiter (Timeout) Config ---
  timelimiter:
    instances:
      default:
        timeoutDuration: 2s # Default timeout [cite: 134]
        
    # --- Retry Config ---
    retry:
      instances:
        default-get:
          maxAttempts: 3 # [cite: 146]
          waitDuration: 500ms # [cite: 148]
          retryExceptions: # [cite: 149]
                          - java.util.concurrent.TimeoutException
                          - java.io.IOException
                          - org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable
          # We only retry idempotent GETs on transient errors

    # --- Circuit Breaker Config ---
    circuitbreaker:
      instances:
        # --- Wallet Service Config ---
        wallet-service:
          slidingWindowType: COUNT_BASED # [cite: 94]
          slidingWindowSize: 10 # [cite: 98]
          failureRateThreshold: 50 # [cite: 100]
          waitDurationInOpenState: 10s # [cite: 106]
          permittedNumberOfCallsInHalfOpenState: 3 # [cite: 107]
          registerHealthIndicator: true # [cite: 116]
          ignoreExceptions: # [cite: 111-114]
                          # These are "business" errors, not system failures.
                          # Do not open the circuit for them.
                          - com.teixeirah.withdrawals.domain.wallet.service.exceptions.WalletNotFoundException
                          - com.teixeirah.withdrawals.domain.wallet.service.exceptions.InsufficientFundsException

