server:
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: wallet-withdrawals
  lifecycle:
    timeout-per-shutdown-phase: 15s
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:walletwithdrawals}
    username: ${DB_USERNAME:walletwithdrawals}
    password: ${DB_PASSWORD:walletwithdrawals}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5

  jooq:
    sql-dialect: postgres
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    validate-migration-naming: true

adapters:
  wallet-service:
    base-url: "${WALLET_SERVICE_URL:http://mockoon.tools.getontop.com:3000/wallets/transactions}"
  payment-provider:
    base-url: "${PAYMENT_PROVIDER_URL:http://mockoon.tools.getontop.com:3000/api/v1/payments}"

payment:
  source:
    type: "${PAYMENT_SOURCE_TYPE:COMPANY}"
    name: "${PAYMENT_SOURCE_NAME:ONTOP INC}"
    account-number: "${PAYMENT_SOURCE_ACCOUNT_NUMBER:0245253419}"
    currency: "${PAYMENT_SOURCE_CURRENCY:USD}"
    routing-number: "${PAYMENT_SOURCE_ROUTING_NUMBER:028444018}"




management:
  endpoints:
    web:
      exposure:
        include: configprops, env, flyway, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  tracing:
    sampling:
      probability: '1.0'
  metrics:
    tags:
      application: ${spring.application.name}

otel:
  propagators:
    - tracecontext
  resource:
    attributes:
      deployment.environment: dev
      service:
        name: ${spring.application.name}
        namespace: teixeirah

