spring:
  application:
    name: wallet-withdrawals
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:walletwithdrawals}
    username: ${DB_USERNAME:walletwithdrawals}
    password: ${DB_PASSWORD:walletwithdrawals}
    driver-class-name: org.postgresql.Driver

  jooq:
    sql-dialect: postgres
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    validate-migration-naming: true

adapters:
  wallet-service:
    base-url: "${WALLET_SERVICE_URL:http://mockoon.tools.getontop.com:3000/wallets/transactions}"
  payment-provider:
    base-url: "${PAYMENT_PROVIDER_URL:http://mockoon.tools.getontop.com:3000/api/v1/payments}"
  wallet-balance:
    base-url: "${WALLET_BALANCE_URL:http://mockoon.tools.getontop.com:3000/wallets/balance}"

payment:
  source:
    type: "${PAYMENT_SOURCE_TYPE:COMPANY}"
    name: "${PAYMENT_SOURCE_NAME:ONTOP INC}"
    account-number: "${PAYMENT_SOURCE_ACCOUNT_NUMBER:0245253419}"
    currency: "${PAYMENT_SOURCE_CURRENCY:USD}"
    routing-number: "${PAYMENT_SOURCE_ROUTING_NUMBER:028444018}"

otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      endpoint: "http://localhost:4318"
  traces:
    sampler:
      probability: 1.0

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        sliding-window-size: 20
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 5
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      walletBalance:
        base-config: default
      paymentProvider:
        base-config: default
      walletService:
        base-config: default
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 500ms
    instances:
      walletBalance:
        base-config: default
      paymentProvider:
        base-config: default
      walletService:
        base-config: default
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 10
        max-wait-duration: 0ms
    instances:
      walletBalance:
        base-config: default
      paymentProvider:
        base-config: default
      walletService:
        base-config: default

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  health:
    circuitbreakers:
      enabled: true
    retries:
      enabled: true
    bulkheads:
      enabled: true
