spring:
  application:
    name: wallet-withdrawals
  threads:
    virtual:
      enabled: true
  datasource:
    write:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:walletwithdrawals}
      username: ${DB_USERNAME:walletwithdrawals}
      password: ${DB_PASSWORD:walletwithdrawals}
      driver-class-name: org.postgresql.Driver
    read:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:walletwithdrawals}
      username: ${DB_USERNAME:walletwithdrawals}
      password: ${DB_PASSWORD:walletwithdrawals}
      driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: postgres
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    validate-migration-naming: true

# Logging
logging:
  level:
    com.teixeirah.withdrawals: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %msg%n"